// Code generated by go-swagger; DO NOT EDIT.

package ui_user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// NewUpdatePasswordUsingPOSTParams creates a new UpdatePasswordUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePasswordUsingPOSTParams() *UpdatePasswordUsingPOSTParams {
	return &UpdatePasswordUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePasswordUsingPOSTParamsWithTimeout creates a new UpdatePasswordUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewUpdatePasswordUsingPOSTParamsWithTimeout(timeout time.Duration) *UpdatePasswordUsingPOSTParams {
	return &UpdatePasswordUsingPOSTParams{
		timeout: timeout,
	}
}

// NewUpdatePasswordUsingPOSTParamsWithContext creates a new UpdatePasswordUsingPOSTParams object
// with the ability to set a context for a request.
func NewUpdatePasswordUsingPOSTParamsWithContext(ctx context.Context) *UpdatePasswordUsingPOSTParams {
	return &UpdatePasswordUsingPOSTParams{
		Context: ctx,
	}
}

// NewUpdatePasswordUsingPOSTParamsWithHTTPClient creates a new UpdatePasswordUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePasswordUsingPOSTParamsWithHTTPClient(client *http.Client) *UpdatePasswordUsingPOSTParams {
	return &UpdatePasswordUsingPOSTParams{
		HTTPClient: client,
	}
}

/*
UpdatePasswordUsingPOSTParams contains all the parameters to send to the API endpoint

	for the update password using p o s t operation.

	Typically these are written to a http.Request.
*/
type UpdatePasswordUsingPOSTParams struct {

	/* UpdatePasswordRequest.

	   updatePasswordRequest
	*/
	UpdatePasswordRequest *models.PasswordChange

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update password using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePasswordUsingPOSTParams) WithDefaults() *UpdatePasswordUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update password using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePasswordUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) WithTimeout(timeout time.Duration) *UpdatePasswordUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) WithContext(ctx context.Context) *UpdatePasswordUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) WithHTTPClient(client *http.Client) *UpdatePasswordUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdatePasswordRequest adds the updatePasswordRequest to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) WithUpdatePasswordRequest(updatePasswordRequest *models.PasswordChange) *UpdatePasswordUsingPOSTParams {
	o.SetUpdatePasswordRequest(updatePasswordRequest)
	return o
}

// SetUpdatePasswordRequest adds the updatePasswordRequest to the update password using p o s t params
func (o *UpdatePasswordUsingPOSTParams) SetUpdatePasswordRequest(updatePasswordRequest *models.PasswordChange) {
	o.UpdatePasswordRequest = updatePasswordRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePasswordUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdatePasswordRequest != nil {
		if err := r.SetBodyParam(o.UpdatePasswordRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
