// Code generated by go-swagger; DO NOT EDIT.

package ui_stack_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClustersOverviewUsingGETParams creates a new GetClustersOverviewUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClustersOverviewUsingGETParams() *GetClustersOverviewUsingGETParams {
	return &GetClustersOverviewUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClustersOverviewUsingGETParamsWithTimeout creates a new GetClustersOverviewUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetClustersOverviewUsingGETParamsWithTimeout(timeout time.Duration) *GetClustersOverviewUsingGETParams {
	return &GetClustersOverviewUsingGETParams{
		timeout: timeout,
	}
}

// NewGetClustersOverviewUsingGETParamsWithContext creates a new GetClustersOverviewUsingGETParams object
// with the ability to set a context for a request.
func NewGetClustersOverviewUsingGETParamsWithContext(ctx context.Context) *GetClustersOverviewUsingGETParams {
	return &GetClustersOverviewUsingGETParams{
		Context: ctx,
	}
}

// NewGetClustersOverviewUsingGETParamsWithHTTPClient creates a new GetClustersOverviewUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClustersOverviewUsingGETParamsWithHTTPClient(client *http.Client) *GetClustersOverviewUsingGETParams {
	return &GetClustersOverviewUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetClustersOverviewUsingGETParams contains all the parameters to send to the API endpoint

	for the get clusters overview using g e t operation.

	Typically these are written to a http.Request.
*/
type GetClustersOverviewUsingGETParams struct {

	/* StackName.

	   stackName
	*/
	StackName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get clusters overview using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClustersOverviewUsingGETParams) WithDefaults() *GetClustersOverviewUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get clusters overview using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClustersOverviewUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) WithTimeout(timeout time.Duration) *GetClustersOverviewUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) WithContext(ctx context.Context) *GetClustersOverviewUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) WithHTTPClient(client *http.Client) *GetClustersOverviewUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStackName adds the stackName to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) WithStackName(stackName string) *GetClustersOverviewUsingGETParams {
	o.SetStackName(stackName)
	return o
}

// SetStackName adds the stackName to the get clusters overview using g e t params
func (o *GetClustersOverviewUsingGETParams) SetStackName(stackName string) {
	o.StackName = stackName
}

// WriteToRequest writes these params to a swagger request
func (o *GetClustersOverviewUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param stackName
	if err := r.SetPathParam("stackName", o.StackName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
