// Code generated by go-swagger; DO NOT EDIT.

package ui_user_vcs_token_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllUsingGET5Params creates a new GetAllUsingGET5Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllUsingGET5Params() *GetAllUsingGET5Params {
	return &GetAllUsingGET5Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllUsingGET5ParamsWithTimeout creates a new GetAllUsingGET5Params object
// with the ability to set a timeout on a request.
func NewGetAllUsingGET5ParamsWithTimeout(timeout time.Duration) *GetAllUsingGET5Params {
	return &GetAllUsingGET5Params{
		timeout: timeout,
	}
}

// NewGetAllUsingGET5ParamsWithContext creates a new GetAllUsingGET5Params object
// with the ability to set a context for a request.
func NewGetAllUsingGET5ParamsWithContext(ctx context.Context) *GetAllUsingGET5Params {
	return &GetAllUsingGET5Params{
		Context: ctx,
	}
}

// NewGetAllUsingGET5ParamsWithHTTPClient creates a new GetAllUsingGET5Params object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllUsingGET5ParamsWithHTTPClient(client *http.Client) *GetAllUsingGET5Params {
	return &GetAllUsingGET5Params{
		HTTPClient: client,
	}
}

/*
GetAllUsingGET5Params contains all the parameters to send to the API endpoint

	for the get all using g e t 5 operation.

	Typically these are written to a http.Request.
*/
type GetAllUsingGET5Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all using g e t 5 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUsingGET5Params) WithDefaults() *GetAllUsingGET5Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all using g e t 5 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUsingGET5Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) WithTimeout(timeout time.Duration) *GetAllUsingGET5Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) WithContext(ctx context.Context) *GetAllUsingGET5Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) WithHTTPClient(client *http.Client) *GetAllUsingGET5Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all using g e t 5 params
func (o *GetAllUsingGET5Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllUsingGET5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
