// Code generated by go-swagger; DO NOT EDIT.

package ui_tf_version_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// SetTfVersionForClusterUsingPUTReader is a Reader for the SetTfVersionForClusterUsingPUT structure.
type SetTfVersionForClusterUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetTfVersionForClusterUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetTfVersionForClusterUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewSetTfVersionForClusterUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSetTfVersionForClusterUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetTfVersionForClusterUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetTfVersionForClusterUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /cc-ui/v1/terraform/cluster/{clusterId}] setTfVersionForClusterUsingPUT", response, response.Code())
	}
}

// NewSetTfVersionForClusterUsingPUTOK creates a SetTfVersionForClusterUsingPUTOK with default headers values
func NewSetTfVersionForClusterUsingPUTOK() *SetTfVersionForClusterUsingPUTOK {
	return &SetTfVersionForClusterUsingPUTOK{}
}

/*
SetTfVersionForClusterUsingPUTOK describes a response with status code 200, with default header values.

OK
*/
type SetTfVersionForClusterUsingPUTOK struct {
	Payload *models.ClusterTfVersionMapping
}

// IsSuccess returns true when this set tf version for cluster using p u t o k response has a 2xx status code
func (o *SetTfVersionForClusterUsingPUTOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set tf version for cluster using p u t o k response has a 3xx status code
func (o *SetTfVersionForClusterUsingPUTOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tf version for cluster using p u t o k response has a 4xx status code
func (o *SetTfVersionForClusterUsingPUTOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set tf version for cluster using p u t o k response has a 5xx status code
func (o *SetTfVersionForClusterUsingPUTOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set tf version for cluster using p u t o k response a status code equal to that given
func (o *SetTfVersionForClusterUsingPUTOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set tf version for cluster using p u t o k response
func (o *SetTfVersionForClusterUsingPUTOK) Code() int {
	return 200
}

func (o *SetTfVersionForClusterUsingPUTOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTOK %s", 200, payload)
}

func (o *SetTfVersionForClusterUsingPUTOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTOK %s", 200, payload)
}

func (o *SetTfVersionForClusterUsingPUTOK) GetPayload() *models.ClusterTfVersionMapping {
	return o.Payload
}

func (o *SetTfVersionForClusterUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterTfVersionMapping)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTfVersionForClusterUsingPUTCreated creates a SetTfVersionForClusterUsingPUTCreated with default headers values
func NewSetTfVersionForClusterUsingPUTCreated() *SetTfVersionForClusterUsingPUTCreated {
	return &SetTfVersionForClusterUsingPUTCreated{}
}

/*
SetTfVersionForClusterUsingPUTCreated describes a response with status code 201, with default header values.

Created
*/
type SetTfVersionForClusterUsingPUTCreated struct {
}

// IsSuccess returns true when this set tf version for cluster using p u t created response has a 2xx status code
func (o *SetTfVersionForClusterUsingPUTCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set tf version for cluster using p u t created response has a 3xx status code
func (o *SetTfVersionForClusterUsingPUTCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tf version for cluster using p u t created response has a 4xx status code
func (o *SetTfVersionForClusterUsingPUTCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this set tf version for cluster using p u t created response has a 5xx status code
func (o *SetTfVersionForClusterUsingPUTCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this set tf version for cluster using p u t created response a status code equal to that given
func (o *SetTfVersionForClusterUsingPUTCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the set tf version for cluster using p u t created response
func (o *SetTfVersionForClusterUsingPUTCreated) Code() int {
	return 201
}

func (o *SetTfVersionForClusterUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTCreated", 201)
}

func (o *SetTfVersionForClusterUsingPUTCreated) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTCreated", 201)
}

func (o *SetTfVersionForClusterUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetTfVersionForClusterUsingPUTUnauthorized creates a SetTfVersionForClusterUsingPUTUnauthorized with default headers values
func NewSetTfVersionForClusterUsingPUTUnauthorized() *SetTfVersionForClusterUsingPUTUnauthorized {
	return &SetTfVersionForClusterUsingPUTUnauthorized{}
}

/*
SetTfVersionForClusterUsingPUTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SetTfVersionForClusterUsingPUTUnauthorized struct {
}

// IsSuccess returns true when this set tf version for cluster using p u t unauthorized response has a 2xx status code
func (o *SetTfVersionForClusterUsingPUTUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tf version for cluster using p u t unauthorized response has a 3xx status code
func (o *SetTfVersionForClusterUsingPUTUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tf version for cluster using p u t unauthorized response has a 4xx status code
func (o *SetTfVersionForClusterUsingPUTUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tf version for cluster using p u t unauthorized response has a 5xx status code
func (o *SetTfVersionForClusterUsingPUTUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this set tf version for cluster using p u t unauthorized response a status code equal to that given
func (o *SetTfVersionForClusterUsingPUTUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the set tf version for cluster using p u t unauthorized response
func (o *SetTfVersionForClusterUsingPUTUnauthorized) Code() int {
	return 401
}

func (o *SetTfVersionForClusterUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTUnauthorized", 401)
}

func (o *SetTfVersionForClusterUsingPUTUnauthorized) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTUnauthorized", 401)
}

func (o *SetTfVersionForClusterUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetTfVersionForClusterUsingPUTForbidden creates a SetTfVersionForClusterUsingPUTForbidden with default headers values
func NewSetTfVersionForClusterUsingPUTForbidden() *SetTfVersionForClusterUsingPUTForbidden {
	return &SetTfVersionForClusterUsingPUTForbidden{}
}

/*
SetTfVersionForClusterUsingPUTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SetTfVersionForClusterUsingPUTForbidden struct {
}

// IsSuccess returns true when this set tf version for cluster using p u t forbidden response has a 2xx status code
func (o *SetTfVersionForClusterUsingPUTForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tf version for cluster using p u t forbidden response has a 3xx status code
func (o *SetTfVersionForClusterUsingPUTForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tf version for cluster using p u t forbidden response has a 4xx status code
func (o *SetTfVersionForClusterUsingPUTForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tf version for cluster using p u t forbidden response has a 5xx status code
func (o *SetTfVersionForClusterUsingPUTForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this set tf version for cluster using p u t forbidden response a status code equal to that given
func (o *SetTfVersionForClusterUsingPUTForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the set tf version for cluster using p u t forbidden response
func (o *SetTfVersionForClusterUsingPUTForbidden) Code() int {
	return 403
}

func (o *SetTfVersionForClusterUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTForbidden", 403)
}

func (o *SetTfVersionForClusterUsingPUTForbidden) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTForbidden", 403)
}

func (o *SetTfVersionForClusterUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSetTfVersionForClusterUsingPUTNotFound creates a SetTfVersionForClusterUsingPUTNotFound with default headers values
func NewSetTfVersionForClusterUsingPUTNotFound() *SetTfVersionForClusterUsingPUTNotFound {
	return &SetTfVersionForClusterUsingPUTNotFound{}
}

/*
SetTfVersionForClusterUsingPUTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type SetTfVersionForClusterUsingPUTNotFound struct {
}

// IsSuccess returns true when this set tf version for cluster using p u t not found response has a 2xx status code
func (o *SetTfVersionForClusterUsingPUTNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set tf version for cluster using p u t not found response has a 3xx status code
func (o *SetTfVersionForClusterUsingPUTNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set tf version for cluster using p u t not found response has a 4xx status code
func (o *SetTfVersionForClusterUsingPUTNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this set tf version for cluster using p u t not found response has a 5xx status code
func (o *SetTfVersionForClusterUsingPUTNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this set tf version for cluster using p u t not found response a status code equal to that given
func (o *SetTfVersionForClusterUsingPUTNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the set tf version for cluster using p u t not found response
func (o *SetTfVersionForClusterUsingPUTNotFound) Code() int {
	return 404
}

func (o *SetTfVersionForClusterUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTNotFound", 404)
}

func (o *SetTfVersionForClusterUsingPUTNotFound) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/terraform/cluster/{clusterId}][%d] setTfVersionForClusterUsingPUTNotFound", 404)
}

func (o *SetTfVersionForClusterUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
