// Code generated by go-swagger; DO NOT EDIT.

package ui_provided_resources_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProvidedResourcesInfoUsingGETParams creates a new GetProvidedResourcesInfoUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProvidedResourcesInfoUsingGETParams() *GetProvidedResourcesInfoUsingGETParams {
	return &GetProvidedResourcesInfoUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProvidedResourcesInfoUsingGETParamsWithTimeout creates a new GetProvidedResourcesInfoUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetProvidedResourcesInfoUsingGETParamsWithTimeout(timeout time.Duration) *GetProvidedResourcesInfoUsingGETParams {
	return &GetProvidedResourcesInfoUsingGETParams{
		timeout: timeout,
	}
}

// NewGetProvidedResourcesInfoUsingGETParamsWithContext creates a new GetProvidedResourcesInfoUsingGETParams object
// with the ability to set a context for a request.
func NewGetProvidedResourcesInfoUsingGETParamsWithContext(ctx context.Context) *GetProvidedResourcesInfoUsingGETParams {
	return &GetProvidedResourcesInfoUsingGETParams{
		Context: ctx,
	}
}

// NewGetProvidedResourcesInfoUsingGETParamsWithHTTPClient creates a new GetProvidedResourcesInfoUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProvidedResourcesInfoUsingGETParamsWithHTTPClient(client *http.Client) *GetProvidedResourcesInfoUsingGETParams {
	return &GetProvidedResourcesInfoUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetProvidedResourcesInfoUsingGETParams contains all the parameters to send to the API endpoint

	for the get provided resources info using g e t operation.

	Typically these are written to a http.Request.
*/
type GetProvidedResourcesInfoUsingGETParams struct {

	/* ClusterID.

	   clusterId
	*/
	ClusterID string

	/* ResourceName.

	   resourceName
	*/
	ResourceName string

	/* ResourceType.

	   resourceType
	*/
	ResourceType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get provided resources info using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvidedResourcesInfoUsingGETParams) WithDefaults() *GetProvidedResourcesInfoUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get provided resources info using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProvidedResourcesInfoUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithTimeout(timeout time.Duration) *GetProvidedResourcesInfoUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithContext(ctx context.Context) *GetProvidedResourcesInfoUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithHTTPClient(client *http.Client) *GetProvidedResourcesInfoUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithClusterID(clusterID string) *GetProvidedResourcesInfoUsingGETParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithResourceName adds the resourceName to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithResourceName(resourceName string) *GetProvidedResourcesInfoUsingGETParams {
	o.SetResourceName(resourceName)
	return o
}

// SetResourceName adds the resourceName to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetResourceName(resourceName string) {
	o.ResourceName = resourceName
}

// WithResourceType adds the resourceType to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) WithResourceType(resourceType string) *GetProvidedResourcesInfoUsingGETParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the get provided resources info using g e t params
func (o *GetProvidedResourcesInfoUsingGETParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WriteToRequest writes these params to a swagger request
func (o *GetProvidedResourcesInfoUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	// path param resourceName
	if err := r.SetPathParam("resourceName", o.ResourceName); err != nil {
		return err
	}

	// path param resourceType
	if err := r.SetPathParam("resourceType", o.ResourceType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
