// Code generated by go-swagger; DO NOT EDIT.

package application_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// NewChangePasswordUsingPUTParams creates a new ChangePasswordUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewChangePasswordUsingPUTParams() *ChangePasswordUsingPUTParams {
	return &ChangePasswordUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewChangePasswordUsingPUTParamsWithTimeout creates a new ChangePasswordUsingPUTParams object
// with the ability to set a timeout on a request.
func NewChangePasswordUsingPUTParamsWithTimeout(timeout time.Duration) *ChangePasswordUsingPUTParams {
	return &ChangePasswordUsingPUTParams{
		timeout: timeout,
	}
}

// NewChangePasswordUsingPUTParamsWithContext creates a new ChangePasswordUsingPUTParams object
// with the ability to set a context for a request.
func NewChangePasswordUsingPUTParamsWithContext(ctx context.Context) *ChangePasswordUsingPUTParams {
	return &ChangePasswordUsingPUTParams{
		Context: ctx,
	}
}

// NewChangePasswordUsingPUTParamsWithHTTPClient creates a new ChangePasswordUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewChangePasswordUsingPUTParamsWithHTTPClient(client *http.Client) *ChangePasswordUsingPUTParams {
	return &ChangePasswordUsingPUTParams{
		HTTPClient: client,
	}
}

/*
ChangePasswordUsingPUTParams contains all the parameters to send to the API endpoint

	for the change password using p u t operation.

	Typically these are written to a http.Request.
*/
type ChangePasswordUsingPUTParams struct {

	/* PwdChange.

	   pwdChange
	*/
	PwdChange *models.PasswordChange

	/* UserID.

	   userId
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the change password using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangePasswordUsingPUTParams) WithDefaults() *ChangePasswordUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the change password using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ChangePasswordUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) WithTimeout(timeout time.Duration) *ChangePasswordUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) WithContext(ctx context.Context) *ChangePasswordUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) WithHTTPClient(client *http.Client) *ChangePasswordUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPwdChange adds the pwdChange to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) WithPwdChange(pwdChange *models.PasswordChange) *ChangePasswordUsingPUTParams {
	o.SetPwdChange(pwdChange)
	return o
}

// SetPwdChange adds the pwdChange to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) SetPwdChange(pwdChange *models.PasswordChange) {
	o.PwdChange = pwdChange
}

// WithUserID adds the userID to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) WithUserID(userID string) *ChangePasswordUsingPUTParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the change password using p u t params
func (o *ChangePasswordUsingPUTParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangePasswordUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PwdChange != nil {
		if err := r.SetBodyParam(o.PwdChange); err != nil {
			return err
		}
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
