// Code generated by go-swagger; DO NOT EDIT.

package ui_accounts_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// CreateAzureAccountUsingPOSTReader is a Reader for the CreateAzureAccountUsingPOST structure.
type CreateAzureAccountUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAzureAccountUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAzureAccountUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewCreateAzureAccountUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateAzureAccountUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateAzureAccountUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateAzureAccountUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cc-ui/v1/accounts/azure/] createAzureAccountUsingPOST", response, response.Code())
	}
}

// NewCreateAzureAccountUsingPOSTOK creates a CreateAzureAccountUsingPOSTOK with default headers values
func NewCreateAzureAccountUsingPOSTOK() *CreateAzureAccountUsingPOSTOK {
	return &CreateAzureAccountUsingPOSTOK{}
}

/*
CreateAzureAccountUsingPOSTOK describes a response with status code 200, with default header values.

OK
*/
type CreateAzureAccountUsingPOSTOK struct {
	Payload *models.AzureAccount
}

// IsSuccess returns true when this create azure account using p o s t o k response has a 2xx status code
func (o *CreateAzureAccountUsingPOSTOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create azure account using p o s t o k response has a 3xx status code
func (o *CreateAzureAccountUsingPOSTOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create azure account using p o s t o k response has a 4xx status code
func (o *CreateAzureAccountUsingPOSTOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create azure account using p o s t o k response has a 5xx status code
func (o *CreateAzureAccountUsingPOSTOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create azure account using p o s t o k response a status code equal to that given
func (o *CreateAzureAccountUsingPOSTOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create azure account using p o s t o k response
func (o *CreateAzureAccountUsingPOSTOK) Code() int {
	return 200
}

func (o *CreateAzureAccountUsingPOSTOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTOK %s", 200, payload)
}

func (o *CreateAzureAccountUsingPOSTOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTOK %s", 200, payload)
}

func (o *CreateAzureAccountUsingPOSTOK) GetPayload() *models.AzureAccount {
	return o.Payload
}

func (o *CreateAzureAccountUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AzureAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAzureAccountUsingPOSTCreated creates a CreateAzureAccountUsingPOSTCreated with default headers values
func NewCreateAzureAccountUsingPOSTCreated() *CreateAzureAccountUsingPOSTCreated {
	return &CreateAzureAccountUsingPOSTCreated{}
}

/*
CreateAzureAccountUsingPOSTCreated describes a response with status code 201, with default header values.

Created
*/
type CreateAzureAccountUsingPOSTCreated struct {
}

// IsSuccess returns true when this create azure account using p o s t created response has a 2xx status code
func (o *CreateAzureAccountUsingPOSTCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create azure account using p o s t created response has a 3xx status code
func (o *CreateAzureAccountUsingPOSTCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create azure account using p o s t created response has a 4xx status code
func (o *CreateAzureAccountUsingPOSTCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create azure account using p o s t created response has a 5xx status code
func (o *CreateAzureAccountUsingPOSTCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create azure account using p o s t created response a status code equal to that given
func (o *CreateAzureAccountUsingPOSTCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create azure account using p o s t created response
func (o *CreateAzureAccountUsingPOSTCreated) Code() int {
	return 201
}

func (o *CreateAzureAccountUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTCreated", 201)
}

func (o *CreateAzureAccountUsingPOSTCreated) String() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTCreated", 201)
}

func (o *CreateAzureAccountUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAzureAccountUsingPOSTUnauthorized creates a CreateAzureAccountUsingPOSTUnauthorized with default headers values
func NewCreateAzureAccountUsingPOSTUnauthorized() *CreateAzureAccountUsingPOSTUnauthorized {
	return &CreateAzureAccountUsingPOSTUnauthorized{}
}

/*
CreateAzureAccountUsingPOSTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateAzureAccountUsingPOSTUnauthorized struct {
}

// IsSuccess returns true when this create azure account using p o s t unauthorized response has a 2xx status code
func (o *CreateAzureAccountUsingPOSTUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create azure account using p o s t unauthorized response has a 3xx status code
func (o *CreateAzureAccountUsingPOSTUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create azure account using p o s t unauthorized response has a 4xx status code
func (o *CreateAzureAccountUsingPOSTUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create azure account using p o s t unauthorized response has a 5xx status code
func (o *CreateAzureAccountUsingPOSTUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create azure account using p o s t unauthorized response a status code equal to that given
func (o *CreateAzureAccountUsingPOSTUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create azure account using p o s t unauthorized response
func (o *CreateAzureAccountUsingPOSTUnauthorized) Code() int {
	return 401
}

func (o *CreateAzureAccountUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTUnauthorized", 401)
}

func (o *CreateAzureAccountUsingPOSTUnauthorized) String() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTUnauthorized", 401)
}

func (o *CreateAzureAccountUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAzureAccountUsingPOSTForbidden creates a CreateAzureAccountUsingPOSTForbidden with default headers values
func NewCreateAzureAccountUsingPOSTForbidden() *CreateAzureAccountUsingPOSTForbidden {
	return &CreateAzureAccountUsingPOSTForbidden{}
}

/*
CreateAzureAccountUsingPOSTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateAzureAccountUsingPOSTForbidden struct {
}

// IsSuccess returns true when this create azure account using p o s t forbidden response has a 2xx status code
func (o *CreateAzureAccountUsingPOSTForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create azure account using p o s t forbidden response has a 3xx status code
func (o *CreateAzureAccountUsingPOSTForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create azure account using p o s t forbidden response has a 4xx status code
func (o *CreateAzureAccountUsingPOSTForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create azure account using p o s t forbidden response has a 5xx status code
func (o *CreateAzureAccountUsingPOSTForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create azure account using p o s t forbidden response a status code equal to that given
func (o *CreateAzureAccountUsingPOSTForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create azure account using p o s t forbidden response
func (o *CreateAzureAccountUsingPOSTForbidden) Code() int {
	return 403
}

func (o *CreateAzureAccountUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTForbidden", 403)
}

func (o *CreateAzureAccountUsingPOSTForbidden) String() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTForbidden", 403)
}

func (o *CreateAzureAccountUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAzureAccountUsingPOSTNotFound creates a CreateAzureAccountUsingPOSTNotFound with default headers values
func NewCreateAzureAccountUsingPOSTNotFound() *CreateAzureAccountUsingPOSTNotFound {
	return &CreateAzureAccountUsingPOSTNotFound{}
}

/*
CreateAzureAccountUsingPOSTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateAzureAccountUsingPOSTNotFound struct {
}

// IsSuccess returns true when this create azure account using p o s t not found response has a 2xx status code
func (o *CreateAzureAccountUsingPOSTNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create azure account using p o s t not found response has a 3xx status code
func (o *CreateAzureAccountUsingPOSTNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create azure account using p o s t not found response has a 4xx status code
func (o *CreateAzureAccountUsingPOSTNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create azure account using p o s t not found response has a 5xx status code
func (o *CreateAzureAccountUsingPOSTNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create azure account using p o s t not found response a status code equal to that given
func (o *CreateAzureAccountUsingPOSTNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create azure account using p o s t not found response
func (o *CreateAzureAccountUsingPOSTNotFound) Code() int {
	return 404
}

func (o *CreateAzureAccountUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTNotFound", 404)
}

func (o *CreateAzureAccountUsingPOSTNotFound) String() string {
	return fmt.Sprintf("[POST /cc-ui/v1/accounts/azure/][%d] createAzureAccountUsingPOSTNotFound", 404)
}

func (o *CreateAzureAccountUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
