// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContainerStatus container status
//
// swagger:model ContainerStatus
type ContainerStatus struct {

	// container ID
	ContainerID string `json:"containerID,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// image ID
	ImageID string `json:"imageID,omitempty"`

	// last state
	LastState *ContainerState `json:"lastState,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// ready
	Ready bool `json:"ready,omitempty"`

	// restart count
	RestartCount int32 `json:"restartCount,omitempty"`

	// started
	Started bool `json:"started,omitempty"`

	// state
	State *ContainerState `json:"state,omitempty"`
}

// Validate validates this container status
func (m *ContainerStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerStatus) validateLastState(formats strfmt.Registry) error {
	if swag.IsZero(m.LastState) { // not required
		return nil
	}

	if m.LastState != nil {
		if err := m.LastState.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastState")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("lastState")
			}
			return err
		}
	}

	return nil
}

func (m *ContainerStatus) validateState(formats strfmt.Registry) error {
	if swag.IsZero(m.State) { // not required
		return nil
	}

	if m.State != nil {
		if err := m.State.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("state")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("state")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this container status based on the context it is used
func (m *ContainerStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerStatus) contextValidateLastState(ctx context.Context, formats strfmt.Registry) error {

	if m.LastState != nil {

		if swag.IsZero(m.LastState) { // not required
			return nil
		}

		if err := m.LastState.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastState")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("lastState")
			}
			return err
		}
	}

	return nil
}

func (m *ContainerStatus) contextValidateState(ctx context.Context, formats strfmt.Registry) error {

	if m.State != nil {

		if swag.IsZero(m.State) { // not required
			return nil
		}

		if err := m.State.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("state")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("state")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerStatus) UnmarshalBinary(b []byte) error {
	var res ContainerStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
