// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GitRepoVolumeSource git repo volume source
//
// swagger:model GitRepoVolumeSource
type GitRepoVolumeSource struct {

	// directory
	Directory string `json:"directory,omitempty"`

	// repository
	Repository string `json:"repository,omitempty"`

	// revision
	Revision string `json:"revision,omitempty"`
}

// Validate validates this git repo volume source
func (m *GitRepoVolumeSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this git repo volume source based on context it is used
func (m *GitRepoVolumeSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GitRepoVolumeSource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitRepoVolumeSource) UnmarshalBinary(b []byte) error {
	var res GitRepoVolumeSource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
