// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HotfixDeploymentRecipe HotfixDeploymentRecipe
//
// swagger:model HotfixDeploymentRecipe
type HotfixDeploymentRecipe struct {

	// resource list
	ResourceList []*FacetsResource `json:"resourceList"`
}

// Validate validates this hotfix deployment recipe
func (m *HotfixDeploymentRecipe) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceList(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HotfixDeploymentRecipe) validateResourceList(formats strfmt.Registry) error {
	if swag.IsZero(m.ResourceList) { // not required
		return nil
	}

	for i := 0; i < len(m.ResourceList); i++ {
		if swag.IsZero(m.ResourceList[i]) { // not required
			continue
		}

		if m.ResourceList[i] != nil {
			if err := m.ResourceList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resourceList" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resourceList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this hotfix deployment recipe based on the context it is used
func (m *HotfixDeploymentRecipe) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResourceList(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HotfixDeploymentRecipe) contextValidateResourceList(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ResourceList); i++ {

		if m.ResourceList[i] != nil {

			if swag.IsZero(m.ResourceList[i]) { // not required
				return nil
			}

			if err := m.ResourceList[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("resourceList" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("resourceList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HotfixDeploymentRecipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HotfixDeploymentRecipe) UnmarshalBinary(b []byte) error {
	var res HotfixDeploymentRecipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
