// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PersistentVolumeDTO persistent volume d t o
//
// swagger:model PersistentVolumeDTO
type PersistentVolumeDTO struct {

	// age in seconds
	AgeInSeconds int64 `json:"ageInSeconds,omitempty"`

	// capacity
	Capacity string `json:"capacity,omitempty"`

	// claim
	Claim string `json:"claim,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// pv access modes
	PvAccessModes []string `json:"pvAccessModes"`

	// reason
	Reason string `json:"reason,omitempty"`

	// reclaim policy
	ReclaimPolicy string `json:"reclaimPolicy,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// storage class
	StorageClass string `json:"storageClass,omitempty"`
}

// Validate validates this persistent volume d t o
func (m *PersistentVolumeDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this persistent volume d t o based on context it is used
func (m *PersistentVolumeDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PersistentVolumeDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersistentVolumeDTO) UnmarshalBinary(b []byte) error {
	var res PersistentVolumeDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
