// Code generated by go-swagger; DO NOT EDIT.

package public_ap_is

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetModuleSchemaParams creates a new GetModuleSchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetModuleSchemaParams() *GetModuleSchemaParams {
	return &GetModuleSchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetModuleSchemaParamsWithTimeout creates a new GetModuleSchemaParams object
// with the ability to set a timeout on a request.
func NewGetModuleSchemaParamsWithTimeout(timeout time.Duration) *GetModuleSchemaParams {
	return &GetModuleSchemaParams{
		timeout: timeout,
	}
}

// NewGetModuleSchemaParamsWithContext creates a new GetModuleSchemaParams object
// with the ability to set a context for a request.
func NewGetModuleSchemaParamsWithContext(ctx context.Context) *GetModuleSchemaParams {
	return &GetModuleSchemaParams{
		Context: ctx,
	}
}

// NewGetModuleSchemaParamsWithHTTPClient creates a new GetModuleSchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetModuleSchemaParamsWithHTTPClient(client *http.Client) *GetModuleSchemaParams {
	return &GetModuleSchemaParams{
		HTTPClient: client,
	}
}

/*
GetModuleSchemaParams contains all the parameters to send to the API endpoint

	for the get module schema operation.

	Typically these are written to a http.Request.
*/
type GetModuleSchemaParams struct {

	// AllowPreview.
	AllowPreview *bool

	// Flavor.
	Flavor string

	// Intent.
	Intent string

	// Version.
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get module schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModuleSchemaParams) WithDefaults() *GetModuleSchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get module schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetModuleSchemaParams) SetDefaults() {
	var (
		allowPreviewDefault = bool(false)
	)

	val := GetModuleSchemaParams{
		AllowPreview: &allowPreviewDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get module schema params
func (o *GetModuleSchemaParams) WithTimeout(timeout time.Duration) *GetModuleSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get module schema params
func (o *GetModuleSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get module schema params
func (o *GetModuleSchemaParams) WithContext(ctx context.Context) *GetModuleSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get module schema params
func (o *GetModuleSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get module schema params
func (o *GetModuleSchemaParams) WithHTTPClient(client *http.Client) *GetModuleSchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get module schema params
func (o *GetModuleSchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAllowPreview adds the allowPreview to the get module schema params
func (o *GetModuleSchemaParams) WithAllowPreview(allowPreview *bool) *GetModuleSchemaParams {
	o.SetAllowPreview(allowPreview)
	return o
}

// SetAllowPreview adds the allowPreview to the get module schema params
func (o *GetModuleSchemaParams) SetAllowPreview(allowPreview *bool) {
	o.AllowPreview = allowPreview
}

// WithFlavor adds the flavor to the get module schema params
func (o *GetModuleSchemaParams) WithFlavor(flavor string) *GetModuleSchemaParams {
	o.SetFlavor(flavor)
	return o
}

// SetFlavor adds the flavor to the get module schema params
func (o *GetModuleSchemaParams) SetFlavor(flavor string) {
	o.Flavor = flavor
}

// WithIntent adds the intent to the get module schema params
func (o *GetModuleSchemaParams) WithIntent(intent string) *GetModuleSchemaParams {
	o.SetIntent(intent)
	return o
}

// SetIntent adds the intent to the get module schema params
func (o *GetModuleSchemaParams) SetIntent(intent string) {
	o.Intent = intent
}

// WithVersion adds the version to the get module schema params
func (o *GetModuleSchemaParams) WithVersion(version string) *GetModuleSchemaParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get module schema params
func (o *GetModuleSchemaParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetModuleSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AllowPreview != nil {

		// query param allowPreview
		var qrAllowPreview bool

		if o.AllowPreview != nil {
			qrAllowPreview = *o.AllowPreview
		}
		qAllowPreview := swag.FormatBool(qrAllowPreview)
		if qAllowPreview != "" {

			if err := r.SetQueryParam("allowPreview", qAllowPreview); err != nil {
				return err
			}
		}
	}

	// path param flavor
	if err := r.SetPathParam("flavor", o.Flavor); err != nil {
		return err
	}

	// path param intent
	if err := r.SetPathParam("intent", o.Intent); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
