// Code generated by go-swagger; DO NOT EDIT.

package ui_o_auth_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// EditGenericOAuthIntegrationUsingPUTReader is a Reader for the EditGenericOAuthIntegrationUsingPUT structure.
type EditGenericOAuthIntegrationUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EditGenericOAuthIntegrationUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEditGenericOAuthIntegrationUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewEditGenericOAuthIntegrationUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEditGenericOAuthIntegrationUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEditGenericOAuthIntegrationUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEditGenericOAuthIntegrationUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /cc-ui/v1/oauth/generic-oauth-integration] editGenericOAuthIntegrationUsingPUT", response, response.Code())
	}
}

// NewEditGenericOAuthIntegrationUsingPUTOK creates a EditGenericOAuthIntegrationUsingPUTOK with default headers values
func NewEditGenericOAuthIntegrationUsingPUTOK() *EditGenericOAuthIntegrationUsingPUTOK {
	return &EditGenericOAuthIntegrationUsingPUTOK{}
}

/*
EditGenericOAuthIntegrationUsingPUTOK describes a response with status code 200, with default header values.

OK
*/
type EditGenericOAuthIntegrationUsingPUTOK struct {
	Payload []*models.CustomOAuth2ClientRegistration
}

// IsSuccess returns true when this edit generic o auth integration using p u t o k response has a 2xx status code
func (o *EditGenericOAuthIntegrationUsingPUTOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edit generic o auth integration using p u t o k response has a 3xx status code
func (o *EditGenericOAuthIntegrationUsingPUTOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit generic o auth integration using p u t o k response has a 4xx status code
func (o *EditGenericOAuthIntegrationUsingPUTOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edit generic o auth integration using p u t o k response has a 5xx status code
func (o *EditGenericOAuthIntegrationUsingPUTOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edit generic o auth integration using p u t o k response a status code equal to that given
func (o *EditGenericOAuthIntegrationUsingPUTOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edit generic o auth integration using p u t o k response
func (o *EditGenericOAuthIntegrationUsingPUTOK) Code() int {
	return 200
}

func (o *EditGenericOAuthIntegrationUsingPUTOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTOK %s", 200, payload)
}

func (o *EditGenericOAuthIntegrationUsingPUTOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTOK %s", 200, payload)
}

func (o *EditGenericOAuthIntegrationUsingPUTOK) GetPayload() []*models.CustomOAuth2ClientRegistration {
	return o.Payload
}

func (o *EditGenericOAuthIntegrationUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEditGenericOAuthIntegrationUsingPUTCreated creates a EditGenericOAuthIntegrationUsingPUTCreated with default headers values
func NewEditGenericOAuthIntegrationUsingPUTCreated() *EditGenericOAuthIntegrationUsingPUTCreated {
	return &EditGenericOAuthIntegrationUsingPUTCreated{}
}

/*
EditGenericOAuthIntegrationUsingPUTCreated describes a response with status code 201, with default header values.

Created
*/
type EditGenericOAuthIntegrationUsingPUTCreated struct {
}

// IsSuccess returns true when this edit generic o auth integration using p u t created response has a 2xx status code
func (o *EditGenericOAuthIntegrationUsingPUTCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edit generic o auth integration using p u t created response has a 3xx status code
func (o *EditGenericOAuthIntegrationUsingPUTCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit generic o auth integration using p u t created response has a 4xx status code
func (o *EditGenericOAuthIntegrationUsingPUTCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this edit generic o auth integration using p u t created response has a 5xx status code
func (o *EditGenericOAuthIntegrationUsingPUTCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this edit generic o auth integration using p u t created response a status code equal to that given
func (o *EditGenericOAuthIntegrationUsingPUTCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the edit generic o auth integration using p u t created response
func (o *EditGenericOAuthIntegrationUsingPUTCreated) Code() int {
	return 201
}

func (o *EditGenericOAuthIntegrationUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTCreated", 201)
}

func (o *EditGenericOAuthIntegrationUsingPUTCreated) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTCreated", 201)
}

func (o *EditGenericOAuthIntegrationUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditGenericOAuthIntegrationUsingPUTUnauthorized creates a EditGenericOAuthIntegrationUsingPUTUnauthorized with default headers values
func NewEditGenericOAuthIntegrationUsingPUTUnauthorized() *EditGenericOAuthIntegrationUsingPUTUnauthorized {
	return &EditGenericOAuthIntegrationUsingPUTUnauthorized{}
}

/*
EditGenericOAuthIntegrationUsingPUTUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type EditGenericOAuthIntegrationUsingPUTUnauthorized struct {
}

// IsSuccess returns true when this edit generic o auth integration using p u t unauthorized response has a 2xx status code
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edit generic o auth integration using p u t unauthorized response has a 3xx status code
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit generic o auth integration using p u t unauthorized response has a 4xx status code
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this edit generic o auth integration using p u t unauthorized response has a 5xx status code
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this edit generic o auth integration using p u t unauthorized response a status code equal to that given
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the edit generic o auth integration using p u t unauthorized response
func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) Code() int {
	return 401
}

func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTUnauthorized", 401)
}

func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTUnauthorized", 401)
}

func (o *EditGenericOAuthIntegrationUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditGenericOAuthIntegrationUsingPUTForbidden creates a EditGenericOAuthIntegrationUsingPUTForbidden with default headers values
func NewEditGenericOAuthIntegrationUsingPUTForbidden() *EditGenericOAuthIntegrationUsingPUTForbidden {
	return &EditGenericOAuthIntegrationUsingPUTForbidden{}
}

/*
EditGenericOAuthIntegrationUsingPUTForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type EditGenericOAuthIntegrationUsingPUTForbidden struct {
}

// IsSuccess returns true when this edit generic o auth integration using p u t forbidden response has a 2xx status code
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edit generic o auth integration using p u t forbidden response has a 3xx status code
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit generic o auth integration using p u t forbidden response has a 4xx status code
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this edit generic o auth integration using p u t forbidden response has a 5xx status code
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this edit generic o auth integration using p u t forbidden response a status code equal to that given
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the edit generic o auth integration using p u t forbidden response
func (o *EditGenericOAuthIntegrationUsingPUTForbidden) Code() int {
	return 403
}

func (o *EditGenericOAuthIntegrationUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTForbidden", 403)
}

func (o *EditGenericOAuthIntegrationUsingPUTForbidden) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTForbidden", 403)
}

func (o *EditGenericOAuthIntegrationUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEditGenericOAuthIntegrationUsingPUTNotFound creates a EditGenericOAuthIntegrationUsingPUTNotFound with default headers values
func NewEditGenericOAuthIntegrationUsingPUTNotFound() *EditGenericOAuthIntegrationUsingPUTNotFound {
	return &EditGenericOAuthIntegrationUsingPUTNotFound{}
}

/*
EditGenericOAuthIntegrationUsingPUTNotFound describes a response with status code 404, with default header values.

Not Found
*/
type EditGenericOAuthIntegrationUsingPUTNotFound struct {
}

// IsSuccess returns true when this edit generic o auth integration using p u t not found response has a 2xx status code
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edit generic o auth integration using p u t not found response has a 3xx status code
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edit generic o auth integration using p u t not found response has a 4xx status code
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edit generic o auth integration using p u t not found response has a 5xx status code
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edit generic o auth integration using p u t not found response a status code equal to that given
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edit generic o auth integration using p u t not found response
func (o *EditGenericOAuthIntegrationUsingPUTNotFound) Code() int {
	return 404
}

func (o *EditGenericOAuthIntegrationUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTNotFound", 404)
}

func (o *EditGenericOAuthIntegrationUsingPUTNotFound) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/oauth/generic-oauth-integration][%d] editGenericOAuthIntegrationUsingPUTNotFound", 404)
}

func (o *EditGenericOAuthIntegrationUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
