// Code generated by go-swagger; DO NOT EDIT.

package ui_common_cluster_controller

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// BulkEditInheritFromBaseForResources1Reader is a Reader for the BulkEditInheritFromBaseForResources1 structure.
type BulkEditInheritFromBaseForResources1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkEditInheritFromBaseForResources1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewBulkEditInheritFromBaseForResources1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBulkEditInheritFromBaseForResources1BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBulkEditInheritFromBaseForResources1Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBulkEditInheritFromBaseForResources1NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewBulkEditInheritFromBaseForResources1MethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkEditInheritFromBaseForResources1InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base] bulkEditInheritFromBaseForResources_1", response, response.Code())
	}
}

// NewBulkEditInheritFromBaseForResources1OK creates a BulkEditInheritFromBaseForResources1OK with default headers values
func NewBulkEditInheritFromBaseForResources1OK() *BulkEditInheritFromBaseForResources1OK {
	return &BulkEditInheritFromBaseForResources1OK{}
}

/*
BulkEditInheritFromBaseForResources1OK describes a response with status code 200, with default header values.

OK
*/
type BulkEditInheritFromBaseForResources1OK struct {
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 o k response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 o k response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 o k response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk edit inherit from base for resources1 o k response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk edit inherit from base for resources1 o k response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the bulk edit inherit from base for resources1 o k response
func (o *BulkEditInheritFromBaseForResources1OK) Code() int {
	return 200
}

func (o *BulkEditInheritFromBaseForResources1OK) Error() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1OK", 200)
}

func (o *BulkEditInheritFromBaseForResources1OK) String() string {
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1OK", 200)
}

func (o *BulkEditInheritFromBaseForResources1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewBulkEditInheritFromBaseForResources1BadRequest creates a BulkEditInheritFromBaseForResources1BadRequest with default headers values
func NewBulkEditInheritFromBaseForResources1BadRequest() *BulkEditInheritFromBaseForResources1BadRequest {
	return &BulkEditInheritFromBaseForResources1BadRequest{}
}

/*
BulkEditInheritFromBaseForResources1BadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type BulkEditInheritFromBaseForResources1BadRequest struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 bad request response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 bad request response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 bad request response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk edit inherit from base for resources1 bad request response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk edit inherit from base for resources1 bad request response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the bulk edit inherit from base for resources1 bad request response
func (o *BulkEditInheritFromBaseForResources1BadRequest) Code() int {
	return 400
}

func (o *BulkEditInheritFromBaseForResources1BadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1BadRequest %s", 400, payload)
}

func (o *BulkEditInheritFromBaseForResources1BadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1BadRequest %s", 400, payload)
}

func (o *BulkEditInheritFromBaseForResources1BadRequest) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *BulkEditInheritFromBaseForResources1BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkEditInheritFromBaseForResources1Forbidden creates a BulkEditInheritFromBaseForResources1Forbidden with default headers values
func NewBulkEditInheritFromBaseForResources1Forbidden() *BulkEditInheritFromBaseForResources1Forbidden {
	return &BulkEditInheritFromBaseForResources1Forbidden{}
}

/*
BulkEditInheritFromBaseForResources1Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type BulkEditInheritFromBaseForResources1Forbidden struct {
	Payload string
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 forbidden response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 forbidden response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 forbidden response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk edit inherit from base for resources1 forbidden response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk edit inherit from base for resources1 forbidden response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the bulk edit inherit from base for resources1 forbidden response
func (o *BulkEditInheritFromBaseForResources1Forbidden) Code() int {
	return 403
}

func (o *BulkEditInheritFromBaseForResources1Forbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1Forbidden %s", 403, payload)
}

func (o *BulkEditInheritFromBaseForResources1Forbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1Forbidden %s", 403, payload)
}

func (o *BulkEditInheritFromBaseForResources1Forbidden) GetPayload() string {
	return o.Payload
}

func (o *BulkEditInheritFromBaseForResources1Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkEditInheritFromBaseForResources1NotFound creates a BulkEditInheritFromBaseForResources1NotFound with default headers values
func NewBulkEditInheritFromBaseForResources1NotFound() *BulkEditInheritFromBaseForResources1NotFound {
	return &BulkEditInheritFromBaseForResources1NotFound{}
}

/*
BulkEditInheritFromBaseForResources1NotFound describes a response with status code 404, with default header values.

Not Found
*/
type BulkEditInheritFromBaseForResources1NotFound struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 not found response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 not found response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 not found response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk edit inherit from base for resources1 not found response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk edit inherit from base for resources1 not found response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the bulk edit inherit from base for resources1 not found response
func (o *BulkEditInheritFromBaseForResources1NotFound) Code() int {
	return 404
}

func (o *BulkEditInheritFromBaseForResources1NotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1NotFound %s", 404, payload)
}

func (o *BulkEditInheritFromBaseForResources1NotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1NotFound %s", 404, payload)
}

func (o *BulkEditInheritFromBaseForResources1NotFound) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *BulkEditInheritFromBaseForResources1NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkEditInheritFromBaseForResources1MethodNotAllowed creates a BulkEditInheritFromBaseForResources1MethodNotAllowed with default headers values
func NewBulkEditInheritFromBaseForResources1MethodNotAllowed() *BulkEditInheritFromBaseForResources1MethodNotAllowed {
	return &BulkEditInheritFromBaseForResources1MethodNotAllowed{}
}

/*
BulkEditInheritFromBaseForResources1MethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type BulkEditInheritFromBaseForResources1MethodNotAllowed struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 method not allowed response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 method not allowed response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 method not allowed response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this bulk edit inherit from base for resources1 method not allowed response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this bulk edit inherit from base for resources1 method not allowed response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the bulk edit inherit from base for resources1 method not allowed response
func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) Code() int {
	return 405
}

func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1MethodNotAllowed %s", 405, payload)
}

func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1MethodNotAllowed %s", 405, payload)
}

func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *BulkEditInheritFromBaseForResources1MethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewBulkEditInheritFromBaseForResources1InternalServerError creates a BulkEditInheritFromBaseForResources1InternalServerError with default headers values
func NewBulkEditInheritFromBaseForResources1InternalServerError() *BulkEditInheritFromBaseForResources1InternalServerError {
	return &BulkEditInheritFromBaseForResources1InternalServerError{}
}

/*
BulkEditInheritFromBaseForResources1InternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type BulkEditInheritFromBaseForResources1InternalServerError struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this bulk edit inherit from base for resources1 internal server error response has a 2xx status code
func (o *BulkEditInheritFromBaseForResources1InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this bulk edit inherit from base for resources1 internal server error response has a 3xx status code
func (o *BulkEditInheritFromBaseForResources1InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this bulk edit inherit from base for resources1 internal server error response has a 4xx status code
func (o *BulkEditInheritFromBaseForResources1InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this bulk edit inherit from base for resources1 internal server error response has a 5xx status code
func (o *BulkEditInheritFromBaseForResources1InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this bulk edit inherit from base for resources1 internal server error response a status code equal to that given
func (o *BulkEditInheritFromBaseForResources1InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the bulk edit inherit from base for resources1 internal server error response
func (o *BulkEditInheritFromBaseForResources1InternalServerError) Code() int {
	return 500
}

func (o *BulkEditInheritFromBaseForResources1InternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1InternalServerError %s", 500, payload)
}

func (o *BulkEditInheritFromBaseForResources1InternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /cc-ui/v1/clusters/{clusterId}/resource-inherit-from-base][%d] bulkEditInheritFromBaseForResources1InternalServerError %s", 500, payload)
}

func (o *BulkEditInheritFromBaseForResources1InternalServerError) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *BulkEditInheritFromBaseForResources1InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
