// Code generated by go-swagger; DO NOT EDIT.

package ui_common_cluster_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAlertsUsingGETParams creates a new GetAlertsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAlertsUsingGETParams() *GetAlertsUsingGETParams {
	return &GetAlertsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAlertsUsingGETParamsWithTimeout creates a new GetAlertsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetAlertsUsingGETParamsWithTimeout(timeout time.Duration) *GetAlertsUsingGETParams {
	return &GetAlertsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetAlertsUsingGETParamsWithContext creates a new GetAlertsUsingGETParams object
// with the ability to set a context for a request.
func NewGetAlertsUsingGETParamsWithContext(ctx context.Context) *GetAlertsUsingGETParams {
	return &GetAlertsUsingGETParams{
		Context: ctx,
	}
}

// NewGetAlertsUsingGETParamsWithHTTPClient creates a new GetAlertsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAlertsUsingGETParamsWithHTTPClient(client *http.Client) *GetAlertsUsingGETParams {
	return &GetAlertsUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetAlertsUsingGETParams contains all the parameters to send to the API endpoint

	for the get alerts using g e t operation.

	Typically these are written to a http.Request.
*/
type GetAlertsUsingGETParams struct {

	/* ClusterID.

	   clusterId
	*/
	ClusterID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get alerts using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlertsUsingGETParams) WithDefaults() *GetAlertsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get alerts using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlertsUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) WithTimeout(timeout time.Duration) *GetAlertsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) WithContext(ctx context.Context) *GetAlertsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) WithHTTPClient(client *http.Client) *GetAlertsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) WithClusterID(clusterID string) *GetAlertsUsingGETParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get alerts using g e t params
func (o *GetAlertsUsingGETParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAlertsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterId
	if err := r.SetPathParam("clusterId", o.ClusterID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
