// Code generated by go-swagger; DO NOT EDIT.

package ui_common_cluster_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// GetProvidedResourcesReader is a Reader for the GetProvidedResources structure.
type GetProvidedResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProvidedResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProvidedResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProvidedResourcesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProvidedResourcesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewGetProvidedResourcesMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProvidedResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cc-ui/v1/clusters/{clusterId}/providedResources] getProvidedResources", response, response.Code())
	}
}

// NewGetProvidedResourcesOK creates a GetProvidedResourcesOK with default headers values
func NewGetProvidedResourcesOK() *GetProvidedResourcesOK {
	return &GetProvidedResourcesOK{}
}

/*
GetProvidedResourcesOK describes a response with status code 200, with default header values.

OK
*/
type GetProvidedResourcesOK struct {
	Payload *models.ProvidedResources
}

// IsSuccess returns true when this get provided resources o k response has a 2xx status code
func (o *GetProvidedResourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get provided resources o k response has a 3xx status code
func (o *GetProvidedResourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get provided resources o k response has a 4xx status code
func (o *GetProvidedResourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get provided resources o k response has a 5xx status code
func (o *GetProvidedResourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get provided resources o k response a status code equal to that given
func (o *GetProvidedResourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get provided resources o k response
func (o *GetProvidedResourcesOK) Code() int {
	return 200
}

func (o *GetProvidedResourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesOK %s", 200, payload)
}

func (o *GetProvidedResourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesOK %s", 200, payload)
}

func (o *GetProvidedResourcesOK) GetPayload() *models.ProvidedResources {
	return o.Payload
}

func (o *GetProvidedResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProvidedResources)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvidedResourcesBadRequest creates a GetProvidedResourcesBadRequest with default headers values
func NewGetProvidedResourcesBadRequest() *GetProvidedResourcesBadRequest {
	return &GetProvidedResourcesBadRequest{}
}

/*
GetProvidedResourcesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetProvidedResourcesBadRequest struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this get provided resources bad request response has a 2xx status code
func (o *GetProvidedResourcesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get provided resources bad request response has a 3xx status code
func (o *GetProvidedResourcesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get provided resources bad request response has a 4xx status code
func (o *GetProvidedResourcesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get provided resources bad request response has a 5xx status code
func (o *GetProvidedResourcesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get provided resources bad request response a status code equal to that given
func (o *GetProvidedResourcesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get provided resources bad request response
func (o *GetProvidedResourcesBadRequest) Code() int {
	return 400
}

func (o *GetProvidedResourcesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesBadRequest %s", 400, payload)
}

func (o *GetProvidedResourcesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesBadRequest %s", 400, payload)
}

func (o *GetProvidedResourcesBadRequest) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *GetProvidedResourcesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvidedResourcesNotFound creates a GetProvidedResourcesNotFound with default headers values
func NewGetProvidedResourcesNotFound() *GetProvidedResourcesNotFound {
	return &GetProvidedResourcesNotFound{}
}

/*
GetProvidedResourcesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetProvidedResourcesNotFound struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this get provided resources not found response has a 2xx status code
func (o *GetProvidedResourcesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get provided resources not found response has a 3xx status code
func (o *GetProvidedResourcesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get provided resources not found response has a 4xx status code
func (o *GetProvidedResourcesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get provided resources not found response has a 5xx status code
func (o *GetProvidedResourcesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get provided resources not found response a status code equal to that given
func (o *GetProvidedResourcesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get provided resources not found response
func (o *GetProvidedResourcesNotFound) Code() int {
	return 404
}

func (o *GetProvidedResourcesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesNotFound %s", 404, payload)
}

func (o *GetProvidedResourcesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesNotFound %s", 404, payload)
}

func (o *GetProvidedResourcesNotFound) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *GetProvidedResourcesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvidedResourcesMethodNotAllowed creates a GetProvidedResourcesMethodNotAllowed with default headers values
func NewGetProvidedResourcesMethodNotAllowed() *GetProvidedResourcesMethodNotAllowed {
	return &GetProvidedResourcesMethodNotAllowed{}
}

/*
GetProvidedResourcesMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type GetProvidedResourcesMethodNotAllowed struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this get provided resources method not allowed response has a 2xx status code
func (o *GetProvidedResourcesMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get provided resources method not allowed response has a 3xx status code
func (o *GetProvidedResourcesMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get provided resources method not allowed response has a 4xx status code
func (o *GetProvidedResourcesMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get provided resources method not allowed response has a 5xx status code
func (o *GetProvidedResourcesMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this get provided resources method not allowed response a status code equal to that given
func (o *GetProvidedResourcesMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the get provided resources method not allowed response
func (o *GetProvidedResourcesMethodNotAllowed) Code() int {
	return 405
}

func (o *GetProvidedResourcesMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesMethodNotAllowed %s", 405, payload)
}

func (o *GetProvidedResourcesMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesMethodNotAllowed %s", 405, payload)
}

func (o *GetProvidedResourcesMethodNotAllowed) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *GetProvidedResourcesMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProvidedResourcesInternalServerError creates a GetProvidedResourcesInternalServerError with default headers values
func NewGetProvidedResourcesInternalServerError() *GetProvidedResourcesInternalServerError {
	return &GetProvidedResourcesInternalServerError{}
}

/*
GetProvidedResourcesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetProvidedResourcesInternalServerError struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this get provided resources internal server error response has a 2xx status code
func (o *GetProvidedResourcesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get provided resources internal server error response has a 3xx status code
func (o *GetProvidedResourcesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get provided resources internal server error response has a 4xx status code
func (o *GetProvidedResourcesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get provided resources internal server error response has a 5xx status code
func (o *GetProvidedResourcesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get provided resources internal server error response a status code equal to that given
func (o *GetProvidedResourcesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get provided resources internal server error response
func (o *GetProvidedResourcesInternalServerError) Code() int {
	return 500
}

func (o *GetProvidedResourcesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesInternalServerError %s", 500, payload)
}

func (o *GetProvidedResourcesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/providedResources][%d] getProvidedResourcesInternalServerError %s", 500, payload)
}

func (o *GetProvidedResourcesInternalServerError) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *GetProvidedResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
