// Code generated by go-swagger; DO NOT EDIT.

package ui_common_cluster_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// ResourceDetailsUsingGETReader is a Reader for the ResourceDetailsUsingGET structure.
type ResourceDetailsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResourceDetailsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResourceDetailsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewResourceDetailsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewResourceDetailsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewResourceDetailsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails] resourceDetailsUsingGET", response, response.Code())
	}
}

// NewResourceDetailsUsingGETOK creates a ResourceDetailsUsingGETOK with default headers values
func NewResourceDetailsUsingGETOK() *ResourceDetailsUsingGETOK {
	return &ResourceDetailsUsingGETOK{}
}

/*
ResourceDetailsUsingGETOK describes a response with status code 200, with default header values.

OK
*/
type ResourceDetailsUsingGETOK struct {
	Payload []*models.ResourceDetails
}

// IsSuccess returns true when this resource details using g e t o k response has a 2xx status code
func (o *ResourceDetailsUsingGETOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this resource details using g e t o k response has a 3xx status code
func (o *ResourceDetailsUsingGETOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resource details using g e t o k response has a 4xx status code
func (o *ResourceDetailsUsingGETOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this resource details using g e t o k response has a 5xx status code
func (o *ResourceDetailsUsingGETOK) IsServerError() bool {
	return false
}

// IsCode returns true when this resource details using g e t o k response a status code equal to that given
func (o *ResourceDetailsUsingGETOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the resource details using g e t o k response
func (o *ResourceDetailsUsingGETOK) Code() int {
	return 200
}

func (o *ResourceDetailsUsingGETOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETOK %s", 200, payload)
}

func (o *ResourceDetailsUsingGETOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETOK %s", 200, payload)
}

func (o *ResourceDetailsUsingGETOK) GetPayload() []*models.ResourceDetails {
	return o.Payload
}

func (o *ResourceDetailsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResourceDetailsUsingGETUnauthorized creates a ResourceDetailsUsingGETUnauthorized with default headers values
func NewResourceDetailsUsingGETUnauthorized() *ResourceDetailsUsingGETUnauthorized {
	return &ResourceDetailsUsingGETUnauthorized{}
}

/*
ResourceDetailsUsingGETUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ResourceDetailsUsingGETUnauthorized struct {
}

// IsSuccess returns true when this resource details using g e t unauthorized response has a 2xx status code
func (o *ResourceDetailsUsingGETUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resource details using g e t unauthorized response has a 3xx status code
func (o *ResourceDetailsUsingGETUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resource details using g e t unauthorized response has a 4xx status code
func (o *ResourceDetailsUsingGETUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this resource details using g e t unauthorized response has a 5xx status code
func (o *ResourceDetailsUsingGETUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this resource details using g e t unauthorized response a status code equal to that given
func (o *ResourceDetailsUsingGETUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the resource details using g e t unauthorized response
func (o *ResourceDetailsUsingGETUnauthorized) Code() int {
	return 401
}

func (o *ResourceDetailsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETUnauthorized", 401)
}

func (o *ResourceDetailsUsingGETUnauthorized) String() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETUnauthorized", 401)
}

func (o *ResourceDetailsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResourceDetailsUsingGETForbidden creates a ResourceDetailsUsingGETForbidden with default headers values
func NewResourceDetailsUsingGETForbidden() *ResourceDetailsUsingGETForbidden {
	return &ResourceDetailsUsingGETForbidden{}
}

/*
ResourceDetailsUsingGETForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ResourceDetailsUsingGETForbidden struct {
}

// IsSuccess returns true when this resource details using g e t forbidden response has a 2xx status code
func (o *ResourceDetailsUsingGETForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resource details using g e t forbidden response has a 3xx status code
func (o *ResourceDetailsUsingGETForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resource details using g e t forbidden response has a 4xx status code
func (o *ResourceDetailsUsingGETForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this resource details using g e t forbidden response has a 5xx status code
func (o *ResourceDetailsUsingGETForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this resource details using g e t forbidden response a status code equal to that given
func (o *ResourceDetailsUsingGETForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the resource details using g e t forbidden response
func (o *ResourceDetailsUsingGETForbidden) Code() int {
	return 403
}

func (o *ResourceDetailsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETForbidden", 403)
}

func (o *ResourceDetailsUsingGETForbidden) String() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETForbidden", 403)
}

func (o *ResourceDetailsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResourceDetailsUsingGETNotFound creates a ResourceDetailsUsingGETNotFound with default headers values
func NewResourceDetailsUsingGETNotFound() *ResourceDetailsUsingGETNotFound {
	return &ResourceDetailsUsingGETNotFound{}
}

/*
ResourceDetailsUsingGETNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ResourceDetailsUsingGETNotFound struct {
}

// IsSuccess returns true when this resource details using g e t not found response has a 2xx status code
func (o *ResourceDetailsUsingGETNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resource details using g e t not found response has a 3xx status code
func (o *ResourceDetailsUsingGETNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resource details using g e t not found response has a 4xx status code
func (o *ResourceDetailsUsingGETNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this resource details using g e t not found response has a 5xx status code
func (o *ResourceDetailsUsingGETNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this resource details using g e t not found response a status code equal to that given
func (o *ResourceDetailsUsingGETNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the resource details using g e t not found response
func (o *ResourceDetailsUsingGETNotFound) Code() int {
	return 404
}

func (o *ResourceDetailsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETNotFound", 404)
}

func (o *ResourceDetailsUsingGETNotFound) String() string {
	return fmt.Sprintf("[GET /cc-ui/v1/clusters/{clusterId}/resourceDetails][%d] resourceDetailsUsingGETNotFound", 404)
}

func (o *ResourceDetailsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
