// Code generated by go-swagger; DO NOT EDIT.

package ui_common_cluster_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Facets-cloud/facets-sdk-go/facets/models"
)

// SetClusterCodeReader is a Reader for the SetClusterCode structure.
type SetClusterCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetClusterCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetClusterCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetClusterCodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetClusterCodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewSetClusterCodeMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetClusterCodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode] setClusterCode", response, response.Code())
	}
}

// NewSetClusterCodeOK creates a SetClusterCodeOK with default headers values
func NewSetClusterCodeOK() *SetClusterCodeOK {
	return &SetClusterCodeOK{}
}

/*
SetClusterCodeOK describes a response with status code 200, with default header values.

OK
*/
type SetClusterCodeOK struct {
	Payload bool
}

// IsSuccess returns true when this set cluster code o k response has a 2xx status code
func (o *SetClusterCodeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set cluster code o k response has a 3xx status code
func (o *SetClusterCodeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set cluster code o k response has a 4xx status code
func (o *SetClusterCodeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set cluster code o k response has a 5xx status code
func (o *SetClusterCodeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set cluster code o k response a status code equal to that given
func (o *SetClusterCodeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set cluster code o k response
func (o *SetClusterCodeOK) Code() int {
	return 200
}

func (o *SetClusterCodeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeOK %s", 200, payload)
}

func (o *SetClusterCodeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeOK %s", 200, payload)
}

func (o *SetClusterCodeOK) GetPayload() bool {
	return o.Payload
}

func (o *SetClusterCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetClusterCodeBadRequest creates a SetClusterCodeBadRequest with default headers values
func NewSetClusterCodeBadRequest() *SetClusterCodeBadRequest {
	return &SetClusterCodeBadRequest{}
}

/*
SetClusterCodeBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SetClusterCodeBadRequest struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this set cluster code bad request response has a 2xx status code
func (o *SetClusterCodeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set cluster code bad request response has a 3xx status code
func (o *SetClusterCodeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set cluster code bad request response has a 4xx status code
func (o *SetClusterCodeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this set cluster code bad request response has a 5xx status code
func (o *SetClusterCodeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this set cluster code bad request response a status code equal to that given
func (o *SetClusterCodeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the set cluster code bad request response
func (o *SetClusterCodeBadRequest) Code() int {
	return 400
}

func (o *SetClusterCodeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeBadRequest %s", 400, payload)
}

func (o *SetClusterCodeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeBadRequest %s", 400, payload)
}

func (o *SetClusterCodeBadRequest) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *SetClusterCodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetClusterCodeNotFound creates a SetClusterCodeNotFound with default headers values
func NewSetClusterCodeNotFound() *SetClusterCodeNotFound {
	return &SetClusterCodeNotFound{}
}

/*
SetClusterCodeNotFound describes a response with status code 404, with default header values.

Not Found
*/
type SetClusterCodeNotFound struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this set cluster code not found response has a 2xx status code
func (o *SetClusterCodeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set cluster code not found response has a 3xx status code
func (o *SetClusterCodeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set cluster code not found response has a 4xx status code
func (o *SetClusterCodeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this set cluster code not found response has a 5xx status code
func (o *SetClusterCodeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this set cluster code not found response a status code equal to that given
func (o *SetClusterCodeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the set cluster code not found response
func (o *SetClusterCodeNotFound) Code() int {
	return 404
}

func (o *SetClusterCodeNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeNotFound %s", 404, payload)
}

func (o *SetClusterCodeNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeNotFound %s", 404, payload)
}

func (o *SetClusterCodeNotFound) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *SetClusterCodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetClusterCodeMethodNotAllowed creates a SetClusterCodeMethodNotAllowed with default headers values
func NewSetClusterCodeMethodNotAllowed() *SetClusterCodeMethodNotAllowed {
	return &SetClusterCodeMethodNotAllowed{}
}

/*
SetClusterCodeMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed
*/
type SetClusterCodeMethodNotAllowed struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this set cluster code method not allowed response has a 2xx status code
func (o *SetClusterCodeMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set cluster code method not allowed response has a 3xx status code
func (o *SetClusterCodeMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set cluster code method not allowed response has a 4xx status code
func (o *SetClusterCodeMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this set cluster code method not allowed response has a 5xx status code
func (o *SetClusterCodeMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this set cluster code method not allowed response a status code equal to that given
func (o *SetClusterCodeMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the set cluster code method not allowed response
func (o *SetClusterCodeMethodNotAllowed) Code() int {
	return 405
}

func (o *SetClusterCodeMethodNotAllowed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeMethodNotAllowed %s", 405, payload)
}

func (o *SetClusterCodeMethodNotAllowed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeMethodNotAllowed %s", 405, payload)
}

func (o *SetClusterCodeMethodNotAllowed) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *SetClusterCodeMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetClusterCodeInternalServerError creates a SetClusterCodeInternalServerError with default headers values
func NewSetClusterCodeInternalServerError() *SetClusterCodeInternalServerError {
	return &SetClusterCodeInternalServerError{}
}

/*
SetClusterCodeInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type SetClusterCodeInternalServerError struct {
	Payload *models.ErrorDetails
}

// IsSuccess returns true when this set cluster code internal server error response has a 2xx status code
func (o *SetClusterCodeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this set cluster code internal server error response has a 3xx status code
func (o *SetClusterCodeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set cluster code internal server error response has a 4xx status code
func (o *SetClusterCodeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this set cluster code internal server error response has a 5xx status code
func (o *SetClusterCodeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this set cluster code internal server error response a status code equal to that given
func (o *SetClusterCodeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the set cluster code internal server error response
func (o *SetClusterCodeInternalServerError) Code() int {
	return 500
}

func (o *SetClusterCodeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeInternalServerError %s", 500, payload)
}

func (o *SetClusterCodeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cc-ui/v1/clusters/{clusterId}/setClusterCode][%d] setClusterCodeInternalServerError %s", 500, payload)
}

func (o *SetClusterCodeInternalServerError) GetPayload() *models.ErrorDetails {
	return o.Payload
}

func (o *SetClusterCodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
